# Generated by Django 3.1.7 on 2021-03-27 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teammembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('phone_number', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('role', models.CharField(default='ADMIN', max_length=64)),
            ],
        ),
    ]
