# Generated by Django 3.1.7 on 2021-03-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'REGULAR'), (1, 'ADMIN')], default=0),
        ),
    ]
